/* COMMENT ON TABLE/COLUMN — sinh bởi docs/build_docs.py từ docs/dictionary_meta.py. Chạy sau 01_ddl.sql */
COMMENT ON TABLE ref.region IS 'Vùng miền dùng để nhóm tỉnh/thành. Grain: 1 dòng / vùng. Căn cứ: Đề xuất của dự án (không có văn bản pháp lý chia 3 miền)';
COMMENT ON TABLE ref.province IS 'Tỉnh/thành phố theo đơn vị hành chính hiện hành (34 đơn vị). Grain: 1 dòng / tỉnh-thành. Căn cứ: NQ 202/2025/QH15';
COMMENT ON TABLE ref.company IS 'Cơ cấu tổ chức: Tổng công ty → khối trụ sở, công ty thành viên, đơn vị kinh doanh số. Grain: 1 dòng / đơn vị. Căn cứ: Mô hình Tổng công ty – công ty thành viên công khai của các DNBH (BCTN Bảo Việt, PVI)';
COMMENT ON TABLE ref.line_of_business IS 'Nghiệp vụ bảo hiểm + nhóm phân tích POC (Xe / Con người / Tài sản). Grain: 1 dòng / nghiệp vụ. Căn cứ: Luật KDBH 2022 Điều 7; NĐ 46/2023/NĐ-CP Điều 4–5';
COMMENT ON TABLE ref.regulatory_line IS 'Dòng báo cáo nghiệp vụ theo mẫu báo cáo Bộ Tài chính (cây cha–con). Grain: 1 dòng / dòng báo cáo. Căn cứ: TT 67/2023/TT-BTC Phụ lục VI – Mẫu 1-PNT/2-PNT';
COMMENT ON TABLE ref.product_group IS 'Nhóm sản phẩm — cấp giữa Nghiệp vụ và Sản phẩm, đúng 8 nhóm của đề bài. Grain: 1 dòng / nhóm SP. Căn cứ: Phạm vi đề bài POC';
COMMENT ON TABLE ref.product IS 'Sản phẩm bảo hiểm (phạm vi POC). Grain: 1 dòng / sản phẩm. Căn cứ: NĐ 67/2023/NĐ-CP; Luật GTGT 48/2024; TT 67/2023/TT-BTC Điều 51';
COMMENT ON TABLE ref.channel IS 'Kênh phân phối theo hình thức cung cấp sản phẩm bảo hiểm. Grain: 1 dòng / kênh. Căn cứ: Luật KDBH 2022 Điều 87 khoản 4; TT 67/2023/TT-BTC Mẫu 3-PNT';
COMMENT ON TABLE ref.partner IS 'Đối tác phân phối (ẩn danh) — ngân hàng, đăng kiểm, OTA, ví điện tử.... Grain: 1 dòng / đối tác. Căn cứ: Loại đối tác theo thực tế thị trường; tên ẩn danh';
COMMENT ON TABLE ref.customer_segment IS 'Phân khúc khách hàng. Grain: 1 dòng / phân khúc. Căn cứ: Phân loại phổ biến (cá nhân / hộ gia đình / doanh nghiệp / cơ quan NN / cơ sở giáo dục)';
COMMENT ON TABLE ref.customer IS 'Khách hàng — bên mua bảo hiểm (dữ liệu giả). Grain: 1 dòng / khách hàng. Căn cứ: Dữ liệu sinh ngẫu nhiên';
COMMENT ON TABLE ref.currency IS 'Tiền tệ. Grain: 1 dòng / loại tiền. Căn cứ: ISO 4217';
COMMENT ON TABLE ref.fx_rate IS 'Tỷ giá hạch toán theo tháng. Grain: 1 dòng / loại tiền × tháng. Căn cứ: Tỷ giá hạch toán KBNN 2025; 2024 ước tính';
COMMENT ON TABLE ref.transaction_type IS 'Loại giao dịch phí: cấp mới, tái tục, SĐBS, hoàn phí, hủy. Grain: 1 dòng / loại giao dịch. Căn cứ: NĐ 46/2023/NĐ-CP Điều 49; TT 232/2012/TT-BTC; ACORD BusinessPurposeTypeCd';
COMMENT ON TABLE ref.insurer IS 'Doanh nghiệp bảo hiểm tham gia đồng bảo hiểm (ẩn danh); OWN = chính công ty. Grain: 1 dòng / DNBH. Căn cứ: Luật KDBH 2022 Điều 4 khoản 29';
COMMENT ON TABLE ref.allocation_type IS 'Loại phân bổ doanh thu giữa các đơn vị. Grain: 1 dòng / loại. Căn cứ: Thông lệ quản trị nội bộ';
COMMENT ON TABLE core.policy IS 'Hợp đồng / đơn bảo hiểm. Grain: 1 dòng / hợp đồng. Căn cứ: Luật KDBH 2022; ACORD Policy; IBM IIW Agreement';
COMMENT ON TABLE core.policy_transaction IS 'Giao dịch phát sinh phí của hợp đồng (cấp mới, tái tục, SĐBS, hoàn phí, hủy). Grain: 1 dòng / giao dịch. Căn cứ: NĐ 46/2023/NĐ-CP Điều 49; TT 232/2012/TT-BTC TK 5111/5311/5321; Microsoft CDM PolicyTransaction';
COMMENT ON TABLE core.transaction_coverage IS 'Phí 100% hợp đồng theo từng sản phẩm của giao dịch. Grain: 1 dòng / giao dịch × sản phẩm. Căn cứ: TT 232/2012/TT-BTC Điều 12 (DT chi tiết theo nghiệp vụ); ACORD Coverage NetChangeAmt';
COMMENT ON TABLE core.coinsurance_share IS 'Tỷ lệ tham gia đồng bảo hiểm của từng DNBH trên hợp đồng (tổng = 100%). Grain: 1 dòng / hợp đồng × DNBH. Căn cứ: Luật KDBH 2022 Điều 4 k29; TT 232/2012/TT-BTC Điều 19; TT 67/2023/TT-BTC Điều 41 k2';
COMMENT ON TABLE core.revenue_allocation IS 'Phân bổ doanh thu phần của công ty cho các đơn vị (tổng = 100%). Grain: 1 dòng / hợp đồng × đơn vị. Căn cứ: Thông lệ quản trị Tổng công ty – công ty thành viên';
COMMENT ON COLUMN ref.region.region_code IS 'Mã vùng: BAC / TRUNG / NAM';
COMMENT ON COLUMN ref.region.region_name IS 'Tên vùng';
COMMENT ON COLUMN ref.province.province_code IS 'Mã tỉnh/thành (mã do dự án đặt, 3 ký tự)';
COMMENT ON COLUMN ref.province.province_name IS 'Tên tỉnh/thành phố [NQ 202/2025/QH15]';
COMMENT ON COLUMN ref.province.region_code IS 'Vùng của tỉnh → ref.region [Đề xuất của dự án]';
COMMENT ON COLUMN ref.company.company_code IS 'Mã đơn vị';
COMMENT ON COLUMN ref.company.company_name IS 'Tên đơn vị (giả lập, đặt theo địa bàn)';
COMMENT ON COLUMN ref.company.company_type IS 'Loại đơn vị: CORPORATION (Tổng công ty) / HEAD_OFFICE (khối trụ sở khai thác trực tiếp) / MEMBER (công ty thành viên) / DIGITAL (đơn vị kinh doanh số)';
COMMENT ON COLUMN ref.company.parent_company_code IS 'Đơn vị cấp trên → ref.company (NULL = Tổng công ty)';
COMMENT ON COLUMN ref.company.province_code IS 'Tỉnh/thành đặt trụ sở → ref.province (NULL = đơn vị không gắn địa bàn)';
COMMENT ON COLUMN ref.company.established_date IS 'Ngày thành lập (giả lập)';
COMMENT ON COLUMN ref.line_of_business.lob_code IS 'Mã nghiệp vụ: SUC_KHOE / XE_CO_GIOI / CHAY_NO / TAI_SAN';
COMMENT ON COLUMN ref.line_of_business.lob_name IS 'Tên nghiệp vụ [NĐ 46/2023/NĐ-CP Điều 4–5]';
COMMENT ON COLUMN ref.line_of_business.legal_category IS 'Loại hình bảo hiểm: Bảo hiểm sức khỏe / Bảo hiểm phi nhân thọ [Luật KDBH 2022 Điều 7 khoản 1]';
COMMENT ON COLUMN ref.line_of_business.poc_group_code IS 'Nhóm phân tích POC: XE / CON_NGUOI / TAI_SAN [Đề bài POC]';
COMMENT ON COLUMN ref.line_of_business.poc_group_name IS 'Tên nhóm phân tích POC [Đề bài POC]';
COMMENT ON COLUMN ref.line_of_business.legal_basis IS 'Căn cứ pháp lý của nghiệp vụ';
COMMENT ON COLUMN ref.regulatory_line.report_line_code IS 'Mã dòng báo cáo (A.1, A.2, B.4a.1 …) — mã do dự án đặt theo thứ tự dòng trong mẫu [TT 67/2023/TT-BTC Phụ lục VI]';
COMMENT ON COLUMN ref.regulatory_line.report_line_name IS 'Tên dòng báo cáo nghiệp vụ [TT 67/2023/TT-BTC Phụ lục VI]';
COMMENT ON COLUMN ref.regulatory_line.parent_line_code IS 'Dòng cha → ref.regulatory_line';
COMMENT ON COLUMN ref.regulatory_line.legal_basis IS 'Căn cứ';
COMMENT ON COLUMN ref.product_group.product_group_code IS 'Mã nhóm SP: TNDS_BB, VCX, HOC_SINH, DU_LICH, SINH_MANG, SUC_KHOE, TAI_SAN, CHAY_NO [Đề bài POC]';
COMMENT ON COLUMN ref.product_group.product_group_name IS 'Tên nhóm sản phẩm';
COMMENT ON COLUMN ref.product_group.lob_code IS 'Nghiệp vụ → ref.line_of_business';
COMMENT ON COLUMN ref.product_group.sort_order IS 'Thứ tự hiển thị';
COMMENT ON COLUMN ref.product.product_code IS 'Mã sản phẩm (tiền tố XE_ / NG_ / TS_ / CHN_)';
COMMENT ON COLUMN ref.product.product_name IS 'Tên sản phẩm theo cách gọi phổ biến của thị trường [Website các DNBH]';
COMMENT ON COLUMN ref.product.product_group_code IS 'Nhóm sản phẩm → ref.product_group';
COMMENT ON COLUMN ref.product.report_line_code IS 'Dòng báo cáo Mẫu 2-PNT → ref.regulatory_line [TT 67/2023/TT-BTC Phụ lục VI]';
COMMENT ON COLUMN ref.product.is_compulsory IS 'TRUE = bảo hiểm bắt buộc [NĐ 67/2023/NĐ-CP]';
COMMENT ON COLUMN ref.product.pricing_basis IS 'Cách tính phí: TARIFF (biểu phí cố định) / RATE_ON_SI (% số tiền BH) / PER_PERSON (theo đầu người)';
COMMENT ON COLUMN ref.product.vat_rate IS 'Thuế suất GTGT %: 0 = không chịu thuế (BH con người), 10 = còn lại [Luật GTGT 48/2024/QH15 Điều 5 khoản 8, Điều 9]';
COMMENT ON COLUMN ref.product.max_commission_pct IS 'Trần tỷ lệ hoa hồng đại lý % [TT 67/2023/TT-BTC Điều 51 khoản 3]';
COMMENT ON COLUMN ref.product.legal_basis IS 'Căn cứ pháp lý riêng của sản phẩm (nếu có)';
COMMENT ON COLUMN ref.product.solvency2_lob IS 'Đối chiếu quốc tế: Solvency II LoB; (*) = suy luận theo bản chất rủi ro [Delegated Reg. (EU) 2015/35 Annex I]';
COMMENT ON COLUMN ref.channel.channel_code IS 'Mã kênh: TRUC_TIEP, DAI_LY_CN, DAI_LY_TC, BANCA, MOI_GIOI, DAU_THAU, DIEN_TU';
COMMENT ON COLUMN ref.channel.channel_name IS 'Tên kênh [Luật KDBH 2022 Điều 87 khoản 4]';
COMMENT ON COLUMN ref.channel.report_channel_group IS 'Nhóm kênh báo cáo: Qua tổ chức tín dụng / Qua môi trường mạng / Qua kênh phân phối khác [TT 67/2023/TT-BTC Mẫu 3-PNT]';
COMMENT ON COLUMN ref.channel.legal_basis IS 'Căn cứ pháp lý của kênh';
COMMENT ON COLUMN ref.channel.sort_order IS 'Thứ tự hiển thị';
COMMENT ON COLUMN ref.partner.partner_code IS 'Mã đối tác';
COMMENT ON COLUMN ref.partner.partner_name IS 'Tên đối tác (ẩn danh: Ngân hàng TMCP A, Ví điện tử B …)';
COMMENT ON COLUMN ref.partner.partner_type IS 'Loại đối tác: NGAN_HANG, CTY_TAI_CHINH, DANG_KIEM, SHOWROOM_OTO, GARAGE, OTA_DU_LICH, CTY_LU_HANH, CTY_MOI_GIOI, VI_DIEN_TU, SAN_TMDT, HANG_HANG_KHONG, VIEN_THONG';
COMMENT ON COLUMN ref.partner.channel_code IS 'Kênh của đối tác → ref.channel';
COMMENT ON COLUMN ref.customer_segment.segment_code IS 'Mã phân khúc';
COMMENT ON COLUMN ref.customer_segment.segment_name IS 'Tên phân khúc';
COMMENT ON COLUMN ref.customer_segment.is_organization IS 'TRUE = tổ chức, FALSE = cá nhân / hộ gia đình';
COMMENT ON COLUMN ref.customer.customer_code IS 'Mã khách hàng (KHnnnnnnn)';
COMMENT ON COLUMN ref.customer.customer_name IS 'Tên khách hàng (giả) [Dữ liệu sinh ngẫu nhiên]';
COMMENT ON COLUMN ref.customer.segment_code IS 'Phân khúc → ref.customer_segment';
COMMENT ON COLUMN ref.customer.tax_code IS 'Mã số thuế (chỉ tổ chức; giả)';
COMMENT ON COLUMN ref.customer.province_code IS 'Tỉnh/thành → ref.province';
COMMENT ON COLUMN ref.customer.home_company_code IS 'Đơn vị quản lý khách hàng → ref.company';
COMMENT ON COLUMN ref.customer.is_aggregated_retail IS 'TRUE = ''Khách lẻ theo bảng kê'' — bên mua gộp của đơn lô giấy chứng nhận bán qua đối tác';
COMMENT ON COLUMN ref.customer.created_date IS 'Ngày tạo khách hàng';
COMMENT ON COLUMN ref.currency.currency_code IS 'Mã tiền tệ ISO 4217';
COMMENT ON COLUMN ref.currency.currency_name IS 'Tên tiền tệ';
COMMENT ON COLUMN ref.fx_rate.currency_code IS 'Tiền tệ → ref.currency';
COMMENT ON COLUMN ref.fx_rate.rate_month IS 'Tháng áp dụng (ngày đầu tháng)';
COMMENT ON COLUMN ref.fx_rate.rate_to_vnd IS 'Tỷ giá quy đổi ra VND [Tỷ giá hạch toán KBNN]';
COMMENT ON COLUMN ref.fx_rate.source_note IS 'Ghi chú nguồn tỷ giá';
COMMENT ON COLUMN ref.transaction_type.txn_type_code IS 'Mã loại giao dịch: NEW, RENEW, END_INC, END_DEC, REFUND, CANCEL, END_NOCHG';
COMMENT ON COLUMN ref.transaction_type.txn_type_name IS 'Tên loại giao dịch';
COMMENT ON COLUMN ref.transaction_type.premium_sign IS 'Dấu của phí: +1 / -1 / 0';
COMMENT ON COLUMN ref.transaction_type.is_revenue_deduction IS 'TRUE = khoản giảm thu (hoàn phí, giảm phí) [NĐ 46/2023/NĐ-CP Điều 49 khoản 3]';
COMMENT ON COLUMN ref.transaction_type.gl_account IS 'Tài khoản kế toán: 5111 phí gốc / 5311 hoàn phí gốc / 5321 giảm phí gốc [TT 232/2012/TT-BTC Điều 2]';
COMMENT ON COLUMN ref.transaction_type.acord_business_purpose_cd IS 'Đối chiếu quốc tế ACORD: NBS / RWL / PCH / XLC [ACORD P&C BusinessPurposeTypeCd]';
COMMENT ON COLUMN ref.transaction_type.note IS 'Ghi chú';
COMMENT ON COLUMN ref.insurer.insurer_code IS 'Mã DNBH; ''OWN'' = chính công ty';
COMMENT ON COLUMN ref.insurer.insurer_name IS 'Tên DNBH (ẩn danh)';
COMMENT ON COLUMN ref.insurer.is_own_company IS 'TRUE = chính công ty';
COMMENT ON COLUMN ref.allocation_type.allocation_type_code IS 'TU_KHAI_THAC / HO_TRO_CHEO / CHUYEN_GIAO';
COMMENT ON COLUMN ref.allocation_type.allocation_type_name IS 'Tên loại phân bổ';
COMMENT ON COLUMN ref.allocation_type.note IS 'Diễn giải';
COMMENT ON COLUMN core.policy.policy_id IS 'Khóa hợp đồng';
COMMENT ON COLUMN core.policy.policy_no IS 'Số hợp đồng: <năm>-<đơn vị>-<nhóm SP>-<số thứ tự>';
COMMENT ON COLUMN core.policy.issuing_company_code IS 'Đơn vị cấp đơn → ref.company';
COMMENT ON COLUMN core.policy.customer_code IS 'Bên mua bảo hiểm → ref.customer';
COMMENT ON COLUMN core.policy.channel_code IS 'Kênh bán → ref.channel. NULL = chưa khai báo (~0,5%, dữ liệu bẩn có chủ đích)';
COMMENT ON COLUMN core.policy.partner_code IS 'Đối tác phân phối → ref.partner (NULL = không qua đối tác)';
COMMENT ON COLUMN core.policy.currency_code IS 'Loại tiền của hợp đồng → ref.currency';
COMMENT ON COLUMN core.policy.issue_date IS 'Ngày cấp đơn / giao kết hợp đồng';
COMMENT ON COLUMN core.policy.effective_date IS 'Ngày bắt đầu thời hạn bảo hiểm';
COMMENT ON COLUMN core.policy.expiry_date IS 'Ngày kết thúc thời hạn bảo hiểm';
COMMENT ON COLUMN core.policy.is_group_policy IS 'TRUE = đơn nhóm / đơn lô giấy chứng nhận';
COMMENT ON COLUMN core.policy.renewal_of_policy_id IS 'Hợp đồng được tái tục → core.policy (NULL = đơn mới)';
COMMENT ON COLUMN core.policy_transaction.txn_id IS 'Khóa giao dịch';
COMMENT ON COLUMN core.policy_transaction.policy_id IS 'Hợp đồng → core.policy';
COMMENT ON COLUMN core.policy_transaction.txn_no IS 'Số chứng từ: <số hợp đồng>/<thứ tự giao dịch>';
COMMENT ON COLUMN core.policy_transaction.txn_type_code IS 'Loại giao dịch → ref.transaction_type';
COMMENT ON COLUMN core.policy_transaction.txn_date IS 'Ngày chứng từ (ngày phát sinh giao dịch)';
COMMENT ON COLUMN core.policy_transaction.accounting_date IS 'Ngày ghi nhận doanh thu = ngày phát sinh trách nhiệm bảo hiểm (cấp mới/tái tục: max(ngày cấp, ngày hiệu lực); SĐBS: ngày chứng từ) [TT 67/2023/TT-BTC Điều 41 khoản 1]';
COMMENT ON COLUMN core.policy_transaction.status IS 'Trạng thái: APPROVED (tính doanh thu) / PENDING / VOID';
COMMENT ON COLUMN core.policy_transaction.fx_rate IS 'Tỷ giá hạch toán tại tháng ghi nhận (VND = 1) [ref.fx_rate]';
COMMENT ON COLUMN core.policy_transaction.created_by IS 'Người tạo chứng từ (giả)';
COMMENT ON COLUMN core.policy_transaction.created_at IS 'Thời điểm tạo chứng từ';
COMMENT ON COLUMN core.transaction_coverage.coverage_id IS 'Khóa dòng phí';
COMMENT ON COLUMN core.transaction_coverage.txn_id IS 'Giao dịch → core.policy_transaction';
COMMENT ON COLUMN core.transaction_coverage.product_code IS 'Sản phẩm → ref.product';
COMMENT ON COLUMN core.transaction_coverage.sum_insured IS 'Số tiền bảo hiểm (nguyên tệ; tổng cho cả lô / nhóm)';
COMMENT ON COLUMN core.transaction_coverage.premium_rate_pct IS 'Tỷ lệ phí % (chỉ sản phẩm tính theo % STBH) [NĐ 67/2023/NĐ-CP PL II (cháy nổ bắt buộc)]';
COMMENT ON COLUMN core.transaction_coverage.insured_count IS 'Số người / xe / giấy chứng nhận được bảo hiểm';
COMMENT ON COLUMN core.transaction_coverage.premium_orig IS 'Phí 100% hợp đồng, nguyên tệ, chưa VAT; là phần THAY ĐỔI phí của giao dịch (âm với giảm/hoàn/hủy) [ACORD Coverage NetChangeAmt]';
COMMENT ON COLUMN core.transaction_coverage.premium_vnd IS 'Phí quy đổi VND, bằng premium_orig × fx_rate';
COMMENT ON COLUMN core.transaction_coverage.vat_vnd IS 'Thuế GTGT (VND) = premium_vnd × vat_rate [Luật GTGT 48/2024]';
COMMENT ON COLUMN core.transaction_coverage.commission_rate_pct IS 'Tỷ lệ hoa hồng % (0 với bán trực tiếp, đấu thầu); ≤ ref.product.max_commission_pct [TT 67/2023/TT-BTC Điều 51]';
COMMENT ON COLUMN core.coinsurance_share.policy_id IS 'Hợp đồng → core.policy';
COMMENT ON COLUMN core.coinsurance_share.insurer_code IS 'DNBH tham gia → ref.insurer (''OWN'' = chính công ty)';
COMMENT ON COLUMN core.coinsurance_share.role IS 'Vai trò: LEADER (đồng chính) / FOLLOWER (đồng phụ) / SOLE (bảo hiểm 100%) [TT 232/2012/TT-BTC Điều 19]';
COMMENT ON COLUMN core.coinsurance_share.share_pct IS 'Tỷ lệ tham gia %; tổng theo hợp đồng = 100 [Luật KDBH 2022 Điều 4 khoản 29]';
COMMENT ON COLUMN core.revenue_allocation.policy_id IS 'Hợp đồng → core.policy';
COMMENT ON COLUMN core.revenue_allocation.company_code IS 'Đơn vị được phân bổ doanh thu → ref.company';
COMMENT ON COLUMN core.revenue_allocation.allocation_type_code IS 'Loại phân bổ → ref.allocation_type';
COMMENT ON COLUMN core.revenue_allocation.allocation_pct IS 'Tỷ lệ phân bổ %; tổng theo hợp đồng = 100';
